# This is the Docker Compose entry point for this project.
# Services listed in this file will automatically be built and started when you bring
# the project up.
version: "3.7"
services:
  python:
    build: ./
    volumes:
      - ./tdd-logs:/tdd-logs:cached
      - ./:/code:cached
      - ./static:/static:cached
    ports:
      - "8801:8801"
    stdin_open: true
    tty: true
